# Generated by Django 4.2 on 2024-08-17 09:20

import apps.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(height_field=350, upload_to=apps.models.apk_file_path, verbose_name='Logo', width_field=320)),
                ('apk_file', models.FileField(upload_to=apps.models.apk_file_path, verbose_name='APK File')),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Other', 'Other')], max_length=50, verbose_name='Platforrm')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='AppTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_title', models.CharField(max_length=50, verbose_name='Test Title')),
                ('tested_at', models.DateTimeField(auto_now=True, verbose_name='Time Tested At')),
                ('first_screen_screenshot', models.FileField(blank=True, null=True, upload_to=apps.models.app_file_path, verbose_name='screen 1')),
                ('second_screen_screenshot', models.FileField(blank=True, null=True, upload_to=apps.models.app_file_path, verbose_name='screen 2')),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.models.app_file_path, verbose_name='video')),
                ('ui_hierarchy', models.FileField(blank=True, null=True, upload_to=apps.models.app_file_path, verbose_name='Ui Hierarchy')),
                ('screen_changed', models.BooleanField(default=False, verbose_name='Screen Changed')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='apps.application', verbose_name='Test')),
            ],
        ),
    ]
