# Generated by Django 4.2 on 2024-08-21 12:26

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_application_logo_subscripedemail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="apptest",
            options={"ordering": ["-tested_at"]},
        ),
        migrations.AlterField(
            model_name="application",
            name="logo",
            field=models.ImageField(
                upload_to=apps.models.apk_file_path, verbose_name="Banner"
            ),
        ),
    ]
